version: '3.8'

services:
  # Nginx service configured to pull from your repository
  nginx:
    image: kowsalyask24/multi-tier-app-nginx:v1
    ports:
      - "80:80"
    depends_on:
      - nodejs
    
  # Node.js service configured to pull from your repository
  nodejs:
    image: kowsalyask24/multi-tier-app-nodejs:v1
    environment:
      # Load environment variables from the .env file
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PORT=${PORT}
    depends_on:
      - mysql
      - redis
    
  # MySQL database service
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    
  # Redis service for caching
  redis:
    image: redis:7.0-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  # Define volumes for data persistence
  mysql_data:
  redis_data:

